import Navbar from "./components/Navbar";
import "./globals.css";
import { Montserrat } from "next/font/google";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Ibrahim Kaiser",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-full min-h-screen bg-[whitesmoke]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
